### PR TITLE
Update price-feed.mdx

### PR DESCRIPTION
**Pull request by neuweltgeld**
BTC token price is null, this may cause misunderstanding. Changed ticker to link. Also ethereum could work.

### CODE REVIEW

**Comment by megabyte0x** [comment]
The `Token` tag is accepting the ticker for the token. Passing the link will break the handler.

**Comment by neuweltgeld** [comment]
token tag remains, link is link token ticker :)

**Comment by megabyte0x** [comment]
ohh okk.. but then I am confused what are you trying to achieve here?

**Comment by neuweltgeld** [comment]
BTC ticker fetching null value, just tried another token price like link or ethereum

**Comment by neuweltgeld** [comment]
too many tester use BTC ticker while using sponsored get content and it is wasting 50 daily quota.

**Comment by megabyte0x** [comment]
understood!
though I would suggest using `ethereum` instead of `link`. It will be easily understandable.

Thanks for this valuable contribution.

**Pull request merged**
